[package]
name = "e_vent_server"
version = "0.1.0"
authors = ["Daniel Tang <danielzgtg.opensource@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.4.0-rc.1", features = ["tls"] }
rocket_contrib = "0.4.0-rc.1"
serde = "1.0"
serde_derive = "1.0"
